import streamlit as st
st.set_page_config(page_title="Meena Mahanth Resume", page_icon="📄", layout="wide")
st.title(":rainbow[Madireddy Meena Mahanth Harinadh]")
st.subheader("AI & Data Science Enthusiast | Python Developer | Prompt Engineer")
st.write("📍 22-55, Batchupeta, Machilipatnam-521001, Andhra Pradesh, India")
st.write("📞 9949447988 | 📧 meenamahanthharinadh@gmail.com")
st.write("[GitHub](https://github.com/meenamahanth) | [LinkedIn](https://linkedin.com/in/madireddy-meena-mahanth-harinadh-0919a3301)")
st.header("🎯 Objective")
st.write("""To secure a position in a progressive organization that allows me to enhance my knowledge and skills,contributing to both personal and organizational growth.""")
st.header("🎓 Education")
st.write("**B.Tech in Artificial Intelligence & Data Science**, Seshadri Rao Gudlavalleru Engineering College (8.73 CGPA)")
st.write("**Intermediate**, Pavithra Junior College (93.3%)")
st.write("**SSC**, Sri Chaitanya Techno School (10.0 GPA)")
st.header("💼 Experience")
st.subheader("AWS Cloud Computing Virtual Internship – Eduskills Foundation")
st.write("""- Developed and optimized data pipelines using AWS S3, RDS, and Redshift.- Used AWS Glue for data cataloging and transformation.- Worked with a team on designing scalable cloud-based solutions.""")
st.header("📂 Projects")
st.subheader("🤖 AI Chatbot – NxtWave Generative AI Workshop")
st.write("""- Built an AI chatbot using Hugging Face, Gradio, Google CodeLab, and OpenAI LLM.- Followed structured guidance by Mr. Abhinav Devaguptapu.- [Try the chatbot here](https://meenamahanth-mygenaichatbot.hf.space)""")
st.header("🎯 Activities")
st.subheader("🔐 Tata Cybersecurity Job Simulation (Forage) – Jan 2025")
st.write("""- Worked on IAM strategy and documentation for a simulated TCS security case.- Gained practical skills in IAM, cybersecurity frameworks, and communication.""")
st.header("📜 Certifications")
st.write("- **C Programming** – JNTUK (June 2023)")
st.write("- **SQL Advanced** – HackerRank (Jan 2025)")
st.write("- **Cybersecurity Analyst** – TCS Forage (Jan 2025)")
st.write("- **Generative AI for All** – Infosys Springboard (Jan 2025)")
st.header("🛠️ Skills")
st.write("""- Artificial Intelligence, Data Science, Machine Learning  - Prompt Engineering, Python, Research & Development  - Teamwork, Time Management""")
st.header("🗣️ Languages")
st.write("Telugu, English, Hindi")
st.markdown("---")
st.caption("Made with ❤️ using Streamlit | Resume of Meena Mahanth Harinadh")
